name: FFmpeg Live Streaming

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:          # تشغيل تلقائي (اختياري)
    - cron: "0 15 * * *" # يوميًا الساعة 15:00 (UTC)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Give execution permissions
      run: chmod +x live.sh

    - name: Start Live Stream
      run: ./live.sh
