name: FFmpeg Live Streaming

on:
  workflow_dispatch: # تشغيل يدوي
  schedule:          # تشغيل تلقائي (اختياري)
    - cron: "0 15 * * *" # يوميًا الساعة 15:00 (UTC)

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install FFmpeg
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Give execution permissions
      run: chmod +x stream2.sh

    - name: Start Live Stream
      run: |
        ffmpeg -i "https://live4.beinconnect.us/YallaGoalApp/beINSports3.m3u8" \
               -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
               -c:a aac -b:a 128k -ac 2 \
               -f flv "rtmps://live-api-s.facebook.com:443/rtmp/FB-122166458174260989-0-AbxTPNanU35-EVYZ"
